# Lấy danh sách tỉnh
# token: eed52935-3a2e-11ed-8063-fa3db46e35b8 ----DEV
# get https://online-gateway.ghn.vn/shiip/public-api/master-data/province
# token: 221a29d9-3a3e-11ed-8008-c673db1cbf27

# Lấy danh sách huyện
# post https://online-gateway.ghn.vn/shiip/public-api/master-data/district
# Content-Type: application/json
# token: 221a29d9-3a3e-11ed-8008-c673db1cbf27

# {"province_id":204}

# Lấy danh sách xã
# post https://online-gateway.ghn.vn/shiip/public-api/master-data/ward?district_id
# Content-Type: application/json
# token: 221a29d9-3a3e-11ed-8008-c673db1cbf27

# {"district_id": 1708}

get me/media?fields=id,caption&access_token=